name: Install LXD runtime dependencies
description: Installs LXD runtime dependencies

runs:
  using: composite
  steps:
    - name: Installs LXD runtime dependencies
      shell: bash
      run: |
        set -eux
        sudo apt-get update

        sudo apt-get install --no-install-recommends -y \
          curl \
          git \
          make \
          acl \
          attr \
          bind9-dnsutils \
          btrfs-progs \
          busybox-static \
          dnsmasq-base \
          easy-rsa \
          gettext \
          jq \
          lvm2 \
          nftables \
          quota \
          rsync \
          s3cmd \
          socat \
          sqlite3 \
          squashfs-tools \
          swtpm \
          tar \
          tcl \
          thin-provisioning-tools \
          uuid-runtime \
          xfsprogs \
          xz-utils \
          zfsutils-linux \
          openvswitch-switch

        if ! command -v yq >/dev/null; then
          # Releases before 24.04 don't have a yq deb so use the snap instead.
          # shellcheck disable=SC1091
          . /etc/os-release
          if dpkg --compare-versions "${VERSION_ID}" ge 24.04; then
              sudo apt-get install --no-install-recommends -y yq
          else
              sudo snap install yq
          fi
        fi

        # reclaim some space
        sudo apt-get clean
