name: Disable Docker
description: Disable Docker and resets the firewall

runs:
  using: composite
  steps:
    - name: Disable Docker
      shell: bash
      run: |
        set -eux
        # disable commands provided by `uidmap` package
        for c in getsubids newgidmap newuidmap; do
          cmd="$(command -v "${c}" || true)"
          [ -n "${cmd}" ] || continue
          [ -x "${cmd}" ] || continue
          sudo chmod -x "${cmd}"
        done

        # disable related units
        for u in containerd.service docker.socket docker.service; do
          sudo systemctl stop "${u}" || true
        done
        sudo ip link delete docker0
        sudo nft flush ruleset || sudo iptables -I DOCKER-USER -j ACCEPT
