name: Install LXD build dependencies
description: Installs LXD build dependencies

runs:
  using: composite
  steps:
    - name: Installs LXD build dependencies
      shell: bash
      run: |
        set -eux
        sudo apt-get update

        sudo apt-get install --no-install-recommends -y \
          autoconf \
          automake \
          build-essential \
          gettext \
          git \
          libacl1-dev \
          libapparmor-dev \
          libcap-dev \
          liblz4-dev \
          libseccomp-dev \
          libsqlite3-dev \
          meson \
          ninja-build \
          python3-venv \
          libtool \
          libudev-dev \
          libuv1-dev \
          make \
          pkg-config \
          shellcheck

        # reclaim some space
        sudo apt-get clean
